name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Install dependencies
        run: go mod tidy

      services:
        redis:
          image: redis
          ports:
            - 6379:6379
          options: >-
            --health-cmd "redis-cli ping"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      - name: Run Tests
        run: go test ./internal/handlers -v

      - name: Show Test Results
        if: failure()
        run: |
          echo "Tests Failed"
          go test ./internal/handlers -v > test_output.log
          cat test_output.log

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test_output.log
